apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eap
resources:
  - namespace.yaml
  - config.yaml
  - data-services.yaml
  - backend.yaml
  - worker.yaml
  - frontend.yaml
  - ingress.yaml
